ADMIN_MENU_IDS = [
    "MainPage", "OntCheck", "Systeminfo", "deviceinfo", "waninfo",
    "opticinfo", "bssinfo", "voipinfo", "ethinfo", "wlaninfo",
    "wlancoverinfo", "osgiplugin", "poeinfo",
    "addconfig", "wanconfig", "lanconfig", "lanportconfig",
    "lanhostconfig", "lanponbind", "landhcp", "landhcpstatic",
    "landhcpv6", "landhcpv6static", "landhcpv6info", "option82",
    "securityconfig", "ipv4firewalllevel", "ipincoming", "macfilter",
    "wlanmacfilter", "parentalctrl", "dos", "portacl", "ontaccess",
    "wanacl", "ipv6ipincoming", "internetcontrol", "globalcontrol", "portcontrol",
    "routeconfig", "ipv4defaultroute", "ipv4staticroute", "ipv4dynamicroute",
    "ipv4vlanbind", "ipv4serviceroute", "ipv4routeinfo",
    "ipv6defaultroute", "ipv6staticroute",
    "forwardrules", "dmz", "portmapping", "porttrigger", "ipv6portmapping",
    "application", "usbapplication", "sntpmngt", "dlnashare", "alg",
    "ddns", "upnp", "igmp", "qossmart", "video", "arp", "dnsconfiguration",
    "wlanconfig", "wlanbasic", "wlanadv", "wlan2basic", "wlan2adv",
    "wlan5basic", "wlan5adv", "wlanschedule", "wificover",
    "voip", "voipinterface", "voipuser", "changeprotocol",
    "systool", "tr069config", "userconfig",
    "passwordcommon",
    "maintaininfo", "fireware", "cfgconfig", "upportconfig",
    "maintainconfig", "userlog", "firewalllog", "debuglog",
    "qossmartstatistics", "collectconfig", "remotepktmirror",
    "testspeed", "sectionspeed", "indicator", "voipstatistic", "voipdiagnosis",
    "poecfg",
    "powercube", "energybaseinfo", "energybasebatteryinfo",
    "energybasewarning", "energybasecfg",
    "bundleconfig", "bundle", "bundleinfo", "bundlestatus", "jvmtatus",
]

ADMIN_ONLY_URLS = [
    "html/bbsp/wan/wan.asp",
    "html/bbsp/layer3/layer3.asp",
    "html/amp/ethponbind/ethponbind.asp",
    "html/bbsp/dhcpstatic/dhcpstatic.asp",
    "html/bbsp/dhcpstaticaddr/dhcpstaticaddress.asp",
    "html/bbsp/dhcp/option82.asp",
    "html/bbsp/firewalllevel/firewalllevel.asp",
    "html/bbsp/Dos/Dos.asp",
    "html/bbsp/portacl/newacl.asp",
    "html/bbsp/acl/aclsmart.asp",
    "html/bbsp/wanacl/wanacl.asp",
    "html/bbsp/internetcontrol/internetcontrol.asp",
    "html/bbsp/8021x/8021x_global.asp",
    "html/bbsp/8021x/8021x_port.asp",
    "html/bbsp/route/route.asp",
    "html/bbsp/staticroute/staticroute.asp",
    "html/bbsp/dynamicroute/dynamicroute.asp",
    "html/bbsp/vlanctc/vlanctc.asp",
    "html/bbsp/serviceroute/serviceroute.asp",
    "html/bbsp/routeinfo/routeinfo.asp",
    "html/bbsp/ipv6defaultroute/defaultroute.asp",
    "html/bbsp/ipv6staticroute/ipv6staticroute.asp",
    "html/bbsp/dmz/dmz.asp",
    "html/bbsp/portmapping/portmapping.asp",
    "html/bbsp/porttrigger/porttrigger.asp",
    "html/bbsp/ipv6portmapping/ipv6portmapping.asp",
    "html/ssmp/sntp/sntp.asp",
    "html/bbsp/alg/alg.asp",
    "html/bbsp/igmp/igmp.asp",
    "html/bbsp/qossmart/qossmart.asp",
    "html/bbsp/video/video.asp",
    "html/bbsp/arpping/arpping.asp",
    "html/bbsp/dnsconfiguration/dnsconfigcommon.asp",
    "html/voip/voipinterface/voipinterface.asp",
    "html/voip/voipuser/voipuser.asp",
    "html/voip/changeprotocol/voipchangeprotocol.asp",
    "html/ssmp/tr069/tr069.asp",
    "html/ssmp/accoutcfg/accountadmin.asp",
    "html/amp/ontauth/passwordcommon.asp",
    "html/ssmp/fireware/firmware.asp",
    "html/ssmp/cfgfile/cfgfile.asp",
    "html/ssmp/mainupportcfg/mainupportconfig.asp",
    "html/ssmp/userlog/logview.asp",
    "html/bbsp/firewalllog/firewalllogview.asp",
    "html/ssmp/debuglog/debuglogview.asp",
    "html/bbsp/qossmartstatistics/qossmartstatistics.asp",
    "html/ssmp/collect/collectInfo.asp",
    "html/bbsp/remotepktmirror/remotepktmirror.asp",
    "html/ssmp/testspeed/testspeed.asp",
    "html/ssmp/Sectionspeed/Sectionspeed.asp",
    "html/voip/statistic/voipstatistic.asp",
    "html/voip/diagnose/voipdiagnose.asp",
    "html/ssmp/smartontinfo/bundle.asp",
    "html/ssmp/smartontinfo/bundleinfo.asp",
    "html/ssmp/energybaseinfo/energybaseinfo.asp",
    "html/ssmp/energybasebatteryinfo/energybasebatteryinfo.asp",
    "html/ssmp/energybasewarning/energybasewarning.asp",
    "html/ssmp/energybasecfg/energybasecfg.asp",
    "html/ssmp/maintain/smartdiagnose.asp",
]

ADMIN_FILES = [
    "/html/ssmp/common/GetUpgradePercent.asp",
    "/html/ssmp/common/GetRestorePercent.asp",
    "/html/ssmp/common/GetBackupPercent.asp",
    "/html/ssmp/fireware/checkforpartition.asp",
    "/html/ssmp/fireware/firmware.asp",
    "/html/ssmp/cfgfile/cfgfile.asp",
    "/html/ssmp/common/GetSwapOldVersion.asp",
    "/html/ssmp/common/getSwapStatus.asp",
    "/html/ssmp/tr069/tr069.asp",
    "/html/ssmp/accoutcfg/accountadmin.asp",
    "/html/ssmp/mainupportcfg/mainupportconfig.asp",
    "/html/ssmp/debuglog/debuglogview.asp",
    "/html/ssmp/userlog/logview.asp",
    "/html/bbsp/firewalllog/firewalllogview.asp",
    "/html/ssmp/collect/collectInfo.asp",
    "/html/ssmp/common/GetSrcInterfaceList.asp",
    "/html/ssmp/testspeed/testspeed.asp",
    "/html/ssmp/Sectionspeed/Sectionspeed.asp",
    "/html/ssmp/common/getTestSpeedResult.asp",
    "/html/ssmp/common/getSectionSpeedResult.asp",
    "/html/bbsp/common/getRouteTable.asp",
    "/html/bbsp/common/getArpStatus.asp",
    "/html/bbsp/common/getDiagStatus.asp",
    "/html/bbsp/common/getTraceStatus.asp",
    "/html/bbsp/common/GetUpgradeStatus.asp",
    "/html/bbsp/qossmartstatistics/qossmartstatistics.asp",
    "/html/bbsp/remotepktmirror/remotepktmirror.asp",
    "/html/voip/statistic/voipstatistic.asp",
    "/html/voip/diagnose/voipdiagnose.asp",
    "/html/amp/ontauth/passwordcommon.asp",
    "/html/ssmp/smartontinfo/bundle.asp",
    "/html/ssmp/smartontinfo/bundleinfo.asp",
    "/html/ssmp/energybaseinfo/energybaseinfo.asp",
    "/html/ssmp/energybasebatteryinfo/energybasebatteryinfo.asp",
    "/html/ssmp/energybasewarning/energybasewarning.asp",
    "/html/ssmp/energybasecfg/energybasecfg.asp",
]
